apiVersion: v1
kind: Secret
metadata:
  name: settleup-secrets
  namespace: settleup
type: Opaque
stringData:
  POSTGRES_DB: settleup
  POSTGRES_USER: settleup_user
  POSTGRES_PASSWORD: change_me
  JWT_SECRET: change_this_in_production
  EMAIL_FROM: no-reply@settleup.local
  SMTP_USER: ""
  SMTP_PASS: ""
